# Generated by Django 5.0 on 2026-02-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_categoriablog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
