# Generated by Django 5.0 on 2026-02-07 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_categoria_imagen_portada_alter_categoria_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='store.producto')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
