# Generated by Django 5.0 on 2026-02-19 04:51

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='autor',
        ),
        migrations.AddField(
            model_name='post',
            name='autor_blog',
            field=models.CharField(choices=[('secretos', 'Secretos Ocultos'), ('jonas', 'Jonás Dante')], default='secretos', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
    ]
